-- Meal Plans Ver1. Paste this entire file into the Supabase SQL Editor.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.meal_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  group_id uuid references public.groups(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 120),
  start_date date not null,
  end_date date not null,
  servings integer check (servings is null or servings >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint meal_plans_seven_days_check
    check (end_date = start_date + 6)
);

create table if not exists public.meal_plan_entries (
  id bigint generated by default as identity primary key,
  meal_plan_id uuid not null references public.meal_plans(id) on delete cascade,
  meal_date date not null,
  meal_type text not null check (meal_type in ('breakfast', 'lunch', 'dinner')),
  recipe_id uuid references public.recipes(id) on delete set null,
  title text not null check (char_length(trim(title)) between 1 and 120),
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists meal_plans_user_start_idx
  on public.meal_plans(user_id, start_date desc);
create index if not exists meal_plans_group_start_idx
  on public.meal_plans(group_id, start_date desc)
  where group_id is not null;
create index if not exists meal_plan_entries_slot_idx
  on public.meal_plan_entries(meal_plan_id, meal_date, meal_type, sort_order);
create index if not exists meal_plan_entries_recipe_idx
  on public.meal_plan_entries(recipe_id)
  where recipe_id is not null;

drop trigger if exists meal_plans_set_updated_at on public.meal_plans;
create trigger meal_plans_set_updated_at before update on public.meal_plans
for each row execute function public.set_updated_at();
drop trigger if exists meal_plan_entries_set_updated_at on public.meal_plan_entries;
create trigger meal_plan_entries_set_updated_at before update on public.meal_plan_entries
for each row execute function public.set_updated_at();

alter table public.meal_plans enable row level security;
alter table public.meal_plan_entries enable row level security;

drop policy if exists "Users can view accessible meal plans" on public.meal_plans;
create policy "Users can view accessible meal plans" on public.meal_plans
for select using (
  user_id = auth.uid()
  or (
    group_id is not null
    and exists (
      select 1 from public.group_members gm
      where gm.group_id = meal_plans.group_id and gm.user_id = auth.uid()
    )
  )
);

drop policy if exists "Users can create meal plans" on public.meal_plans;
create policy "Users can create meal plans" on public.meal_plans
for insert with check (
  user_id = auth.uid()
  and (
    group_id is null
    or exists (
      select 1 from public.group_members gm
      where gm.group_id = meal_plans.group_id and gm.user_id = auth.uid()
    )
  )
);

drop policy if exists "Creators can update meal plans" on public.meal_plans;
create policy "Creators can update meal plans" on public.meal_plans
for update using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and (
    group_id is null
    or exists (
      select 1 from public.group_members gm
      where gm.group_id = meal_plans.group_id and gm.user_id = auth.uid()
    )
  )
);

drop policy if exists "Creators can delete meal plans" on public.meal_plans;
create policy "Creators can delete meal plans" on public.meal_plans
for delete using (user_id = auth.uid());

drop policy if exists "Users can view accessible meal entries" on public.meal_plan_entries;
create policy "Users can view accessible meal entries" on public.meal_plan_entries
for select using (exists (
  select 1 from public.meal_plans mp
  where mp.id = meal_plan_id
    and (
      mp.user_id = auth.uid()
      or exists (
        select 1 from public.group_members gm
        where gm.group_id = mp.group_id and gm.user_id = auth.uid()
      )
    )
));

drop policy if exists "Creators can insert meal entries" on public.meal_plan_entries;
create policy "Creators can insert meal entries" on public.meal_plan_entries
for insert with check (exists (
  select 1 from public.meal_plans mp
  where mp.id = meal_plan_id
    and mp.user_id = auth.uid()
    and meal_date between mp.start_date and mp.end_date
));

drop policy if exists "Creators can update meal entries" on public.meal_plan_entries;
create policy "Creators can update meal entries" on public.meal_plan_entries
for update using (exists (
  select 1 from public.meal_plans mp
  where mp.id = meal_plan_id and mp.user_id = auth.uid()
)) with check (exists (
  select 1 from public.meal_plans mp
  where mp.id = meal_plan_id
    and mp.user_id = auth.uid()
    and meal_date between mp.start_date and mp.end_date
));

drop policy if exists "Creators can delete meal entries" on public.meal_plan_entries;
create policy "Creators can delete meal entries" on public.meal_plan_entries
for delete using (exists (
  select 1 from public.meal_plans mp
  where mp.id = meal_plan_id and mp.user_id = auth.uid()
));
