-- Recipe notes: paste this entire file into the Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 120),
  image_url text,
  image_path text,
  source_url text check (
    source_url is null
    or source_url ~* '^https?://'
  ),
  instructions text,
  memo text,
  is_favorite boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recipe_items (
  id bigint generated by default as identity primary key,
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  item_master_id bigint not null references public.item_master(id),
  item_type text not null check (item_type in ('ingredient', 'seasoning')),
  amount_text text not null default '',
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recipe_items_recipe_master_unique unique (recipe_id, item_master_id)
);

create index if not exists recipes_user_updated_idx
  on public.recipes(user_id, updated_at desc);
create index if not exists recipes_user_favorite_idx
  on public.recipes(user_id, is_favorite) where is_favorite = true;
create index if not exists recipe_items_recipe_sort_idx
  on public.recipe_items(recipe_id, sort_order);
create index if not exists recipe_items_master_idx
  on public.recipe_items(item_master_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists recipes_set_updated_at on public.recipes;
create trigger recipes_set_updated_at before update on public.recipes
for each row execute function public.set_updated_at();
drop trigger if exists recipe_items_set_updated_at on public.recipe_items;
create trigger recipe_items_set_updated_at before update on public.recipe_items
for each row execute function public.set_updated_at();

alter table public.recipes enable row level security;
alter table public.recipe_items enable row level security;

drop policy if exists "Users can select own recipes" on public.recipes;
create policy "Users can select own recipes" on public.recipes
for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own recipes" on public.recipes;
create policy "Users can insert own recipes" on public.recipes
for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update own recipes" on public.recipes;
create policy "Users can update own recipes" on public.recipes
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can delete own recipes" on public.recipes;
create policy "Users can delete own recipes" on public.recipes
for delete using (auth.uid() = user_id);

drop policy if exists "Users can select own recipe items" on public.recipe_items;
create policy "Users can select own recipe items" on public.recipe_items
for select using (exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
));
drop policy if exists "Users can insert own recipe items" on public.recipe_items;
create policy "Users can insert own recipe items" on public.recipe_items
for insert with check (exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
));
drop policy if exists "Users can update own recipe items" on public.recipe_items;
create policy "Users can update own recipe items" on public.recipe_items
for update using (exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
)) with check (exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
));
drop policy if exists "Users can delete own recipe items" on public.recipe_items;
create policy "Users can delete own recipe items" on public.recipe_items
for delete using (exists (
  select 1 from public.recipes r
  where r.id = recipe_id and r.user_id = auth.uid()
));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'recipe-images',
  'recipe-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view recipe images" on storage.objects;
create policy "Public can view recipe images" on storage.objects
for select using (bucket_id = 'recipe-images');
drop policy if exists "Users can upload own recipe images" on storage.objects;
create policy "Users can upload own recipe images" on storage.objects
for insert to authenticated with check (
  bucket_id = 'recipe-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "Users can update own recipe images" on storage.objects;
create policy "Users can update own recipe images" on storage.objects
for update to authenticated using (
  bucket_id = 'recipe-images'
  and (storage.foldername(name))[1] = auth.uid()::text
) with check (
  bucket_id = 'recipe-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "Users can delete own recipe images" on storage.objects;
create policy "Users can delete own recipe images" on storage.objects
for delete to authenticated using (
  bucket_id = 'recipe-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);
